services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wordpress:/var/www/html
      - ../:/var/www/html/wp-content/plugins/fapi-member
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    container_name: wordpress-db
    image: mysql:8
    restart: always
    platform: linux/amd64
    ports:
      - "3307:3306"
      - "13307:3306"
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql

  node:
    build:
      context: node
    container_name: node
    user: "root"
    working_dir: /var/www/html/wp-content/plugins/fapi-member
    volumes:
      - ../:/var/www/html/wp-content/plugins/fapi-member
    ports:
      - "8099:8099"
    expose:
      - "8099"
    restart: always
    entrypoint: /opt/node.sh

volumes:
  wordpress:
  db:
  node:
